# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LeasewebCli < Formula
  desc "The command line interface for Leaseweb API"
  homepage "https://github.com/Nmishin/leaseweb-cli"
  version "1.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.5/leaseweb-cli-1.2.5-darwin-x86_64.tar.gz"
      sha256 "f63ca0bd26bbeed60993cafa18ce8cdb60da20ca0858555f6fc0db3119e48424"

      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.5/leaseweb-cli-1.2.5-darwin-arm64.tar.gz"
      sha256 "21f95553d35ea432cb943d2ba97eed06861ff8e21177dcfbe94de5e595482ddc"

      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.5/leaseweb-cli-1.2.5-linux-x86_64.tar.gz"
      sha256 "70bc2129994019c2a6e34764d752c55cd7988eed73854853ed6c67d7b66f0426"
      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.5/leaseweb-cli-1.2.5-linux-arm64.tar.gz"
      sha256 "d44bc3f5583ac1ce94572c39cd701b0ad786e8bba8aa7667229e13924970e74e"
      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
  end
end
