# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LeasewebCli < Formula
  desc "The command line interface for Leaseweb API"
  homepage "https://github.com/Nmishin/leaseweb-cli"
  version "1.2.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.4/leaseweb-cli-1.2.4-darwin-x86_64.tar.gz"
      sha256 "d567b2d023c12b41baea2981229382b792c83fc198138b8039bd6b6f1345cee7"

      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.4/leaseweb-cli-1.2.4-darwin-arm64.tar.gz"
      sha256 "f03c6fa9e5068f4d5108204861bfc3a4f1691320e9c059bc3dc3f5fbc5f74707"

      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.4/leaseweb-cli-1.2.4-linux-x86_64.tar.gz"
      sha256 "738f6975dc1bcad72d7bce4bb065222587b68e7eee3e4e1b45bfdf57ec9a188a"
      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.4/leaseweb-cli-1.2.4-linux-arm64.tar.gz"
      sha256 "4996419eb5084fbd6f4271505dbc7e99b37c6bf365fb27b5d50c184024f9219a"
      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
  end
end
