# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LeasewebCli < Formula
  desc "The command line interface for Leaseweb API"
  homepage "https://github.com/Nmishin/leaseweb-cli"
  version "1.2.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.8/leaseweb-cli-1.2.8-darwin-x86_64.tar.gz"
      sha256 "4cba96d57d5b5f8c7732777253f8f5b1315207917fc422819f44e7297d52501c"

      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.8/leaseweb-cli-1.2.8-darwin-arm64.tar.gz"
      sha256 "63cc24a74cfda95f82c145742271fa340bb17a4f0f01fd8cfef9aa53a409749b"

      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.8/leaseweb-cli-1.2.8-linux-x86_64.tar.gz"
      sha256 "e13aab39929ad1243d3b301b834948c212cb8a003dde512b53859fb81d69c14d"
      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/leaseweb-cli/releases/download/v1.2.8/leaseweb-cli-1.2.8-linux-arm64.tar.gz"
      sha256 "bec7534f9d263492c74da7cf67f161f35cb76957b8d1ba8b6bf64201d72a5627"
      def install
        bin.install "leaseweb-cli"
        chmod 0555, bin/"leaseweb-cli"
      end
    end
  end
end
