# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mustreveal < Formula
  desc "Tool for reveal (decrypt) obscured rclone configuration."
  homepage "https://github.com/Nmishin/mustreveal"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nmishin/mustreveal/releases/download/v0.1.5/mustreveal_Darwin_x86_64.tar.gz"
      sha256 "e10cc827deab36b43b6539e40b9415c7753825f075bdfa0656cd83fbce69e829"

      def install
        bin.install "mustreveal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nmishin/mustreveal/releases/download/v0.1.5/mustreveal_Darwin_arm64.tar.gz"
      sha256 "bc4559c944cc7459dd0b9a0ad2f8018eece4cdda419001ea8f50f7478af80755"

      def install
        bin.install "mustreveal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/mustreveal/releases/download/v0.1.5/mustreveal_Linux_x86_64.tar.gz"
      sha256 "e03f35b5208ab3c68be55664af87a4ab61daf87503fd31b3529253b938b3b3aa"
      def install
        bin.install "mustreveal"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Nmishin/mustreveal/releases/download/v0.1.5/mustreveal_Linux_arm64.tar.gz"
      sha256 "5c42faa11365c9b6f37a127617b62d001699a3cd12b32910ecc851ca2b88ea59"
      def install
        bin.install "mustreveal"
      end
    end
  end
end
